# Generated by Django 2.2.6 on 2019-10-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_user', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('pregunta_1', models.CharField(max_length=20)),
                ('pregunta_2', models.CharField(max_length=20)),
                ('pregunta_3', models.CharField(max_length=20)),
                ('pregunta_4', models.CharField(max_length=20)),
                ('pregunta_5', models.CharField(max_length=20)),
            ],
        ),
    ]
